### ISSUE TITLE
Symbolic coefficients in polynomial expressions

### ISSUE THREAD

**Issue by vyudu** [saschatimme/MixedSubdivisions.jl#27]
Hello! Is there a way to have a polynomial with some symbolic coefficients (like `a*x^2 + b*x + c`). as an input to the `mixed_volume`? I am starting with a Symbolics expression but am unsure whether it's possible to convert it to a DynamicPolynomial while keeping the coefficients as symbolic. This would be quite useful for calculations for chemical reaction network steady states.

Apologies in advance if this issue is misplaced, but thought it might be a useful case for this package since I believe the mixed volume doesn't actually depend on the coefficients?

**Comment by saschatimme** [comment]
I think all function that accept a polynomial also accept a matrix representing the support of the polynomial. Usually the conversion is done internally by using the [support](https://github.com/saschatimme/MixedSubdivisions.jl/blob/84f5a4528b067f60021d96406be7ce8019b7bb5c/src/MixedSubdivisions.jl#L1394) function. This also accepts the variables of the polynomial which in your `a*x^2 + b*x + c` example would be just `[x]`.

**Comment by vyudu** [comment]
Ah, I see, thank you!
